### ISSUE TITLE
Does this raml tutorial still work? I am getting the following errors?

### ISSUE THREAD

**Issue by gkimpson** [lukaswhite/raml-test-example#1]
I've followed the tutorial here http://www.sitepoint.com/testing-apis-raml/ - and i've had a few problems getting this to work. I am using the code from the github repo and have turned on server using the command below:
    php -S localhost:8000

When I go to this URI (or use Postman) I get the following error messages, can you suggest how I may fix/get around these problems? Thanks in advance.

`Warning: Illegal offset type in isset or empty in C:\src\ramltests\vendor\nikic\fast-route\src\DataGenerator\RegexBasedAbstract.php on line 61

Warning: Illegal offset type in C:\src\ramltests\vendor\nikic\fast-route\src\DataGenerator\RegexBasedAbstract.php on line 72

Warning: Illegal offset type in isset or empty in C:\src\ramltests\vendor\nikic\fast-route\src\DataGenerator\RegexBasedAbstract.php on line 54

Warning: Illegal offset type in isset or empty in C:\src\ramltests\vendor\nikic\fast-route\src\DataGenerator\RegexBasedAbstract.php on line 61

Warning: Illegal offset type in C:\src\ramltests\vendor\nikic\fast-route\src\DataGenerator\RegexBasedAbstract.php on line 72

Warning: Illegal offset type in C:\src\ramltests\vendor\nikic\fast-route\src\DataGenerator\RegexBasedAbstract.php on line 78

Warning: Illegal offset type in C:\src\ramltests\vendor\nikic\fast-route\src\DataGenerator\RegexBasedAbstract.php on line 85`

**Comment by gkimpson** [comment]
-- update --
I have changed the error_reporting to 0 in the index.php and now I get the following errors:-

`[Tue Mar 15 11:38:45 2016] ::1:4537 [200]: /index.php - Uncaught exception 'Symfony\Component\Yaml\Exception\ParseException' with message 'Unable to parse at line 15 (near "/account:php").' in C:\src\ramltests\vendor\symfony\yaml\Parser.php:298
Stack trace:
#0 C:\src\ramltests\vendor\symfony\yaml\Yaml.php(65): Symfony\Component\Yaml\Parser->parse('#%RAML 0.8\ntitl...', true, true, false)
#1 C:\src\ramltests\vendor\alecsammon\php-raml-parser\src\Parser.php(491): Symfony\Component\Yaml\Yaml::parse('#%RAML 0.8\ntitl...', true, true)
#2 C:\src\ramltests\vendor\alecsammon\php-raml-parser\src\Parser.php(462): Raml\Parser->parseYaml('#%RAML 0.8\ntitl...')
#3 C:\src\ramltests\vendor\alecsammon\php-raml-parser\src\Parser.php(203): Raml\Parser->parseRamlString('#%RAML 0.8\ntitl...', 'C:\\src\\ramltest...')
#4 C:\src\ramltests\src\Sitepoint\RamlApiMock.php(14): Raml\Parser->parse('./test/fixture/...')
#5 C:\src\ramltests\index.php(11): Sitepoint\RamlApiMock->__construct('./test/fixture/...')
#6 {main}
  thrown in C:\src\ramltests\vendor\symfony\yaml\Parser.php on line 298
`

Can you suggest anything at all? Thanks

**Comment by lukaswhite** [comment]
Hi there

I tried a fresh install and got the same errors; the version I had sitting around on my machine worked fine.

Looks like the problem is probably something to do with the `php-raml-parser` package; this repo currently uses the `dev-master` version, so somewhere along the line there must have been a breaking change.

What I've done is commit my `composer.lock`, so if you try running `composer install` now, it should use the same version of `php-raml-parser` as I used when I first wrote this.
